services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: ["./run.sh"]
    depends_on:
      - db
  db:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
        - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: