services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    env_file:
      - .env
    command: ["./run.sh"]
    depends_on:
      - db
  db:
    image: postgres:17.0-alpine3.20
    env_file:
      - .env
    volumes:
        - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: