# Generated by Django 5.1.1 on 2024-10-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50)),
                ('em_uso', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('automatico', models.BooleanField(default=False)),
                ('responsavel', models.CharField(max_length=100)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('tamanho_ram', models.CharField(max_length=100)),
                ('tamanho_hd', models.CharField(max_length=100)),
                ('modelo_cpu', models.CharField(max_length=100)),
                ('ultimo_usuario_logado', models.CharField(max_length=100)),
                ('valido', models.BooleanField(default=False)),
                ('sistema_operacional', models.CharField(max_length=100)),
                ('placa_mae', models.CharField(max_length=100)),
                ('criticidade_dados', models.CharField(choices=[('ALTA', 'Alta Prioridade'), ('MEDIA', 'Média Prioridade'), ('BAIXA', 'Baixa Prioridade')], default='BAIXA', max_length=50)),
                ('ativos_relacionados', models.ManyToManyField(blank=True, to='lotus.computador')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='LicencaSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('quantidade_em_uso', models.IntegerField()),
                ('data_expiracao', models.DateField()),
                ('descricao', models.TextField()),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus.computador')),
            ],
            options={
                'verbose_name': 'Licença de Software',
                'verbose_name_plural': 'Licenças de Software',
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versao', models.CharField(max_length=100)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus.computador')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus.bloco')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50)),
                ('em_uso', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('automatico', models.BooleanField(default=False)),
                ('responsavel', models.CharField(max_length=100)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('resolucao', models.CharField(max_length=100)),
                ('ativos_relacionados', models.ManyToManyField(blank=True, to='lotus.monitor')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotus.sala')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50)),
                ('em_uso', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('automatico', models.BooleanField(default=False)),
                ('responsavel', models.CharField(max_length=100)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('ativos_relacionados', models.ManyToManyField(blank=True, to='lotus.impressora')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotus.sala')),
            ],
            options={
                'verbose_name': 'Impressora',
                'verbose_name_plural': 'Impressoras',
            },
        ),
        migrations.AddField(
            model_name='computador',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotus.sala'),
        ),
    ]
