# Generated by Django 5.1.1 on 2024-12-02 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(max_length=100)),
                ('movimentacao_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotus.movimentacao')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotus.sala')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.DeleteModel(
            name='ComputadorCompletosProxy',
        ),
        migrations.CreateModel(
            name='ComputadorValidosProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Computador Valido',
                'verbose_name_plural': 'Computadores Validos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lotus.computador',),
        ),
        migrations.AddField(
            model_name='computador',
            name='ultima_movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotus.movimentacao'),
        ),
        migrations.AddField(
            model_name='impressora',
            name='ultima_movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotus.movimentacao'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='ultima_movimentacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lotus.movimentacao'),
        ),
    ]
