# Generated by Django 5.1.1 on 2024-12-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotus', '0002_movimentacao_delete_computadorcompletosproxy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimentacao',
            old_name='sala',
            new_name='sala_atual',
        ),
    ]
